name: OWASP ZAP DAST

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 0'  # Runs weekly on Sunday at 4 AM

jobs:
  dast-zap-scan:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: cdn
        options: >-
          --health-cmd="mariadb-admin ping -h localhost -u root -ppassword"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=15
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t cdn-backend ./backend

      - name: Start backend container
        run: |
          docker run -d \
            --name backend-container \
            --network host \
            -p 5000:5000 \
            -e DATABASE_HOST=localhost \
            -e DATABASE_PORT=3306 \
            -e DATABASE_USER=root \
            -e DATABASE_PASSWORD=password \
            -e DATABASE_NAME=cdn \
            cdn-backend

      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5000 > /dev/null 2>&1; then
              echo "Application is ready"
              exit 0
            fi
            echo "Waiting for application... ($i/30)"
            sleep 2
          done
          echo "Application failed to start"
          exit 1

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://host.docker.internal:5000'
          cmd_options: '-a'
          allow_issue_writing: false   # prevent the action from writing Issues/PR comments

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            report_html.html
            report_md.md
            report_json.json
          retention-days: 30

      - name: Display ZAP Summary
        if: always()
        run: |
          echo "=== OWASP ZAP DAST Scan Complete ==="
          echo "Full reports available in artifacts: zap-scan-report"
          echo "Target: http://localhost:5000"
